Repository mistakia/nano-community, pull requests merged in 2024-03, with the labels that each got.

#82 Create nano-reps.csv
  data/nano-reps.csv
Labels: need/triage

#85 Update nano-reps.csv
  data/nano-reps.csv
Labels: need/triage

#86 Update nano-reps.csv
  data/nano-reps.csv
Labels: need/triage

#90 updating ip and node names of humble nodes
  data/representative-mappings.json
Labels: need/triage

#89 chore: update `data/representative-mappings.json`
  data/representative-mappings.json
  scripts/generate-rep-mappings.mjs
Labels: priority/medium, kind/maintenance, status/in-progress

#96 docs: fix typos
  docs/design/challenges.md
  docs/design/glossary.md
  docs/getting-started-devs/getting-started.md
Labels: need/triage

#104 feat: create `/live` page
  src/core/api/index.js
  src/core/api/reducer.js
  src/core/api/sagas.js
  src/core/api/selectors.js
  src/core/api/service.js
  src/core/nanodb/actions.js
  src/core/nanodb/index.js
  src/core/nanodb/reducer.js
  src/core/nanodb/sagas.js
  src/core/reducers.js
  src/core/sagas.js
  src/styles/toggle-button-group.styl
  src/styles/variables.styl
  src/views/components/app/app.js
  src/views/components/metric-card/metric-card.js
  src/views/components/metric-card/metric-card.styl
  src/views/components/posts/posts.js
  src/views/components/posts/posts.styl
  src/views/pages/live/index.js
  src/views/pages/live/live.js
  src/views/pages/live/live.styl
  src/views/routes.js
Labels: priority/medium, kind/enhancement, status/in-progress

#84 feat: added `generate-nano-reps` script
  common/index.mjs
  common/read-csv.mjs
  data/nano-reps.csv
  db/schema.sql
  package.json
  scripts/generate-nano-reps.mjs
  yarn.lock
Labels: priority/medium, kind/maintenance, status/in-progress
